# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  workflow_dispatch:

env:
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release_MD
  BUILD_PLUGIN_CONFIGURATION: Release

  GIT_TVTEST_NAME: TVTest
  GIT_TVTEST_REF: develop
  GIT_TVTEST_PLATFORM: "'Win32', 'x64'"

  # https://github.com/mstorsjo/fdk-aac
  GIT_FDK_AAC_REF: v2.0.3

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 20

    strategy:
      matrix:
        platform: [x86, x64]

    env:
      GIT_TVTEST_PLATFORM: ${{ matrix.platform == 'x86' && 'Win32' || matrix.platform }}

    steps:
    - name: Test
      env:
        GIT_TVTEST_PLATFORM: ${{ matrix.platform == 'x86' && 'Win32' || matrix.platform }}
      run: |
        Write-Host $Env:GIT_TVTEST_PLATFORM

    - name: Test2
      run: |
        Write-Host $Env:GIT_TVTEST_PLATFORM
