# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  workflow_dispatch:

env:
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release_MD

  # https://github.com/mstorsjo/fdk-aac
  GIT_FDK_AAC_REF: v2.0.3

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 20

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: DBCTRADO/TVTest
        ref: develop

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 17
        msbuild-architecture: x64

    - name: Sets
      shell: cmd
      run: |
        set
        dir

    - name: Pre-Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        git submodule set-branch --branch develop src/LibISDB
        git submodule update --init --depth 1 src/LibISDB
        Set-Location src\LibISDB
        git submodule update --init Thirdparty/fdk-aac
        Set-Location Thirdparty\fdk-aac
        git checkout $Env:GIT_FDK_AAC_REF
        Set-Location ..\..\..\..\
        foreach ($platform in ('x86', 'x64')) {msbuild -maxCpuCount -target:Build -property:Configuration=$Env:BUILD_CONFIGURATION -property:Platform=$platform src\LibISDB\Projects\LibISDB.sln}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        msbuild -maxCpuCount -target:Build -property:Configuration=$Env:BUILD_CONFIGURATION -property:Platform=Win32 src\TVTest.sln

#    - name: Packing
